### PR TITLE
Updating to node v20

### PR DESCRIPTION
**Pull request by tegefaulkes**
### Description

In this PR we are updating to node 20. This includes nix changes and package updates.

### Issues Fixed

* This doesn't directly fix any issues

### Tasks

1. [X] Update nix config to use node 20
2. [X] Update node dependencies to the appropriate versions. Using js-quic as reference.
3. [X] Build with the new version
4. [x] make sure all tests are working.

### Final checklist

* [x] Domain specific tests
* [x] Full tests
* [x] Updated inline-comment documentation
* [x] Lint fixed
* [x] Squash and rebased
* [x] Sanity check the final build

### CODE REVIEW

**Comment by tegefaulkes** [comment]
Same problems as https://github.com/MatrixAI/js-db/pull/69, this is the source of it.

**Comment by tegefaulkes** [comment]
Running a test.ts script that just `console.log`s and running it with `npm run ts-node -- test.ts` results in the same error. I've test that here and in `Polykey` with the same results.

So it seems ts-node is broken. Seems to not be transpiling with swc properly. This is broken in polykey repo and presumably everywhere we've updated to node 20 so far. I think the only reason it was revealed here is because of it being run on the worker script.

**Comment by tegefaulkes** [comment]
https://github.com/swc-project/swc/issues/7923 

Seems relevant. Pinning the version of `@swc/core` to `1.3.82` fixes the problem.

**Comment by CMCDragonkai** [comment]
The latest `@swc/core` that I have currently is `^1.3.76`. Should we update to `^1.3.82`?

**Comment by CMCDragonkai** [comment]
Oh I think I understand, apparently a later version of swc has a problem, and they want to rollback something or until ts-node fixes this https://github.com/TypeStrong/ts-node/pull/2057.

Then we just have to pin it to 1.3.82, the 1 patch version before that change that introduced that issue.

On a side note, the ESM branches I've already stopped using `ts-node` and swapped to `tsx` which works for ESM stuff.

**Comment by tegefaulkes** [comment]
Yep, the fix for now is pinning to `1.3.82`. I'll make that change and apply it to the other repos as well.

**Comment by tegefaulkes** [comment]
All fixed, Merging.

**Comment by CMCDragonkai** [comment]
> [swc-project/swc#7923](https://github.com/swc-project/swc/issues/7923)
> 
> Seems relevant. Pinning the version of `@swc/core` to `1.3.82` fixes the problem.

@amydevs @addievo - apply this to js-ws and js-rpc. I'll be doing this for js-quic.

**Pull request merged**
